version: "3.9"
services:
  refact_self_hosted:
    image: smallcloud/refact_self_hosting:latest
    volumes:
      - perm_storage:/perm_storage
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro


#  cassandra:
#    image: bitnami/cassandra:latest
#    volumes:
#      - cassandra_storage:/bitnami
#    ports:
#      - '9042:9042' # comment on prod, debug only!


volumes:
  perm_storage:
#  cassandra_storage:
